### ISSUE TITLE
Matting color different depending on mat type or random?

### ISSUE THREAD

**Issue by sapnho** [helgeerbe/picframe#90]
@jgodfrey This is not a bug report but just a question out of curiosity: Is the matting color depending on the mat type or is it sometimes randomized?

I am asking because I got two very different results for the same image and the only difference was the mat type:

![Matting-Picture-Frame-Raspberry-Pi-5](https://user-images.githubusercontent.com/33040431/112716795-d0b4d180-8ee8-11eb-9619-68f921adc1bc.jpg)
![IMG_4793](https://user-images.githubusercontent.com/33040431/112716800-d1e5fe80-8ee8-11eb-8158-75d0c3d41e46.jpeg)

**Comment by paddywwoof** [comment]
The colour is determined by taking three randomly selected pixels initially then grouping all the pixels by how close they are to each of those three. The the three RGB values are taken as the average of each group and the process repeated. After a few cycles the colors partition themselves into groups of similar colours which are then sorted according to how non-grey they are. Obviously it does depend on what the initial pixels are but quite often the mean of each cluster 'migrates' towards the same value.

It might be more consistent if we started with more than three points - I don't think it would have much impact on processing time. Also we don' really take account of colour perception in judging the non-greyness so [230, 255, 230] would score 25 higher than [50, 74, 50] scoring 24
![swatch](https://user-images.githubusercontent.com/1939398/112719984-cc41e600-8ef3-11eb-8ee8-9df632e9c70f.png)

**Comment by jgodfrey** [comment]
Yep, Paddy's description is exactly correct. It's that initial "random" selection of 3 pixels that causes the solution to sometimes differ for the same image. Really, the algorithm used here (kmeans clustering) is intended to be iterative. That is, it's meant to be run over and over and over again until the solution stabilizes (pixels are no longer shifted between the color buckets). While that would provide a much more repeatable solution, it's also much more expensive. Because of that, many implementations (including ours) just run some predetermined number of iterations and call the solution "good enough". If it were allowed to run longer, the final color selection should be more repeatable - so really, it's a _solution quality_ versus _time_ tradeoff. 

@paddywwoof - perhaps with the `numpy` implementation, we could afford a few more iterations? Though, I'm not sure it's necessary.

Another option to stabilize the color for a given image would be to store it in the cache and not calculate it again. Originally, I intended to do exactly that because the original implementation was _really_ expensive (and slow). But, with the `numpy` implementation, it was fast enough to just run _on-the-fly_, so no value storage necessary.

**Comment by sapnho** [comment]
Thanks, guys, for the great explanation. It's great as it is already!

**Comment by jgodfrey** [comment]
Seems like we're all in agreement here. Closing this one.
